# Generated by Django 4.0.4 on 2022-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FI', 'fiction'), ('NF', 'non-fiction')], max_length=2, null=True),
        ),
    ]
